Add block/unblock and reset all

diff --git a/jerk b/jerk
--- a/jerk
+++ b/jerk
@@ -1,13 +1,16 @@
 #!/bin/bash
 
+# Remount rootfs as read-only when script exits
+trap remountRootfsROIfNecessary EXIT
 
 # Constant values
-VERSION="1.0.0"
+VERSION="1.0.1"
 BACKUP_SUFFIX=".JERKORIG"
 ORIG_FOLDERNAME="ORIG"
 MOD_FOLDERNAME="MOD"
 PASSWORD_PROMPT="A process needs root access. Please input your password: "
 CFG_FOLDER="components"
+BLOCK_OTA_PKG="BlockOTA.jerk"
 
 # Initialize variables
 SCRIPT=$( basename "$0" )
@@ -16,6 +19,7 @@ VERBOSE_MODE=0
 FORCE_MODE=0
 SCRIPT_REMOUNTED_ROOTFS=0
 TARGET_COMPONENT_PROVIDED=0
+SAY_YES_MODE=0
 
 # Display version.
 function Version
@@ -30,22 +34,30 @@ function Help
 {
    # Display Help
    echo "Jerk is a tool for installing and uninstalling simple custom patches in an Ubuntu Touch system."
+   echo "Using this tool via SSH is highly recommended especially when dealing with components such as Lomiri"
    echo
-   echo "Usage: $SCRIPT <Options>[-h|V|v|f|d] <Command>[check|install|reset|uninstall|describe] <Package Name/Target Component>"
+   echo "Usage: $SCRIPT <Options>[-h|V|v|f|d|y] <Command>[check|install|reset|uninstall|describe|block-ota|unblock-ota] <Package Name/Target Component>"
    echo
    echo "Commands:"
    echo "check          Check if the package is compatible with your system"
    echo "install        Install the specified package to your system."
+   echo "               Automatically blocks OTA updates"
    echo "reset          Revert all changes in the target path of the specified package or component."
    echo "               Restores files using the '$BACKUP_SUFFIX' files."
    echo "               New files installed by packages won't be removed"
    echo "               'uninstall' is recommended for a cleaner uninstallation"
+   echo "               Run '$SCRIPT reset all' to reset all known components which also unblocks OTA updates"
    echo "               Valid components:"
    echo "               "$(ls $CFG_FOLDER | sed 's/\.cfg$//')
    echo "uninstall      Revert changes based on the files in the specified package."
    echo "               Restore files using the '$BACKUP_SUFFIX' files."
    echo "describe       Display details about the specified package if there's any."
    echo "               This may include new features, fixes and changes implemented by the package"
+   echo "block-ota      Installs a package to block OTA updates."
+   echo "               This is to avoid installing an OTA update that can possibly have conflict with installed packages."
+   echo "unblock-ota    Removes the package that blocks OTA updates."
+   echo "               This is only recommended if you're sure there's no more installed packages."
+   echo "               Running '$SCRIPT reset all' is recommended which also unblocks OTA updates."
    echo
    echo "Options:"
    echo "--help, -h        Print help text."
@@ -53,6 +65,7 @@ function Help
    echo "--verbose, -v     Verbose mode."
    echo "--force, -f       Ignore incompatibilities and force installation"
    echo "--debug, -d       Debug mode. Only log actions and no actual execution"
+   echo "--say-yes, -y     Skip all prompts, if any, by saying yes to all"
    echo
 }
 
@@ -280,25 +293,30 @@ function validateInput
             fi
         else
             if [ "$PROCESS_MODE" = "reset" ]; then
-                getComponentConfigValues $PACKAGE_NAME # Load config from the specified component
-                if [ $? -eq 0 ]; then
-                    TARGET_PATH=$(echo $target_path | sed 's/\/$//') # Last "/" is removed if there's any
-                else
-                    echo "Target component is invalid."
-                    echo "Valid values:"
-                    echo $(ls $CFG_FOLDER | sed 's/\.cfg$//')
-                    exit 1
-                fi
-
-                if [ -n "$TARGET_PATH" ]; then
-                    showDebug "Mode: $PROCESS_MODE"
-                    showDebug "Target Component: $PACKAGE_NAME"
-                    showDebug "Target Path: $TARGET_PATH"
+                if [ "$PACKAGE_NAME" = "all" ]; then
                     TARGET_COMPONENT_PROVIDED=1
                     return_code=0
                 else
-                    echo "Script config error. Please report to the $SCRIPT developer"
-                    exit 1
+                    getComponentConfigValues $PACKAGE_NAME # Load config from the specified component
+                    if [ $? -eq 0 ]; then
+                        TARGET_PATH=$(echo $target_path | sed 's/\/$//') # Last "/" is removed if there's any
+                    else
+                        echo "Target component is invalid."
+                        echo "Valid values:"
+                        echo $(ls $CFG_FOLDER | sed 's/\.cfg$//')
+                        exit 1
+                    fi
+
+                    if [ -n "$TARGET_PATH" ]; then
+                        showDebug "Mode: $PROCESS_MODE"
+                        showDebug "Target Component: $PACKAGE_NAME"
+                        showDebug "Target Path: $TARGET_PATH"
+                        TARGET_COMPONENT_PROVIDED=1
+                        return_code=0
+                    else
+                        echo "Script config error. Please report to the $SCRIPT developer"
+                        exit 1
+                    fi
                 fi
             else
                 echo "Package file does not exist."
@@ -317,11 +335,13 @@ function validateInput
 function runPostInstall
 {
     if [[ -v post_install ]]; then
-        read -p "Instalation requires to run a command to take effect (Command: $post_install). Run now? (y/Y): " -r
-        if [[ $REPLY =~ ^[Yy]$ ]]; then
+        if [ $SAY_YES_MODE -eq 0 ]; then
+            read -p "Instalation requires to run a command to take effect (Command: $post_install). Run now? (y/Y): " -r
+        fi
+        if [ $SAY_YES_MODE -eq 1 ] || [[ $REPLY =~ ^[Yy]$ ]]; then
             showVerbose "Running post instalation command '$post_install' "
             if [ $DEBUG_MODE -eq 0 ]; then
-                $post_install
+                eval "$post_install" #FIXME: Can be dangerous
             fi
         fi
     fi
@@ -464,8 +484,12 @@ function backup_files
     checkIfBackUpExists
 
     if [ $? -eq 1 ]; then
-        read -p "Some backup files already exists in your system. These will be overwritten. Continue? (y/Y): " -r
-        if [[ $REPLY =~ ^[Yy]$ ]]; then
+        if [ $SAY_YES_MODE -eq 0 ]; then
+            read -p "Some backup files already exists in your system. These will be overwritten. Continue? (y/Y): " -r
+            if [[ $REPLY =~ ^[Yy]$ ]]; then
+                continueProcess=0
+            fi
+        else
             continueProcess=0
         fi
     else
@@ -560,7 +584,7 @@ function reset_path
     backupfiles_list=()
     while IFS=  read -r -d $'\0'; do
         backupfiles_list+=("$REPLY")
-    done < <(find $1 -name "*${BACKUP_SUFFIX}" -print0)
+    done < <(sudo -p "$PASSWORD_PROMPT" find $1 -name "*${BACKUP_SUFFIX}" -print0)
 
     if [ ${#backupfiles_list[@]} -eq 0 ]; then
         echo "Nothing to reset"
@@ -591,13 +615,14 @@ for arg in "$@"; do
     "--version")   set -- "$@" "-V" ;;
     "--force")   set -- "$@" "-f" ;;
     "--debug")   set -- "$@" "-d" ;;
+    "--say-yes")   set -- "$@" "-y" ;;
     *)        set -- "$@" "$arg"
   esac
 done
 
 # Parse short options
 OPTIND=1
-while getopts ":hvVfd" opt
+while getopts ":hvVfdy" opt
 do
   case "$opt" in
     "h") Help; exit 0 ;;
@@ -605,6 +630,7 @@ do
     "v") VERBOSE_MODE=1;;
     "f") FORCE_MODE=1;;
     "d") DEBUG_MODE=1;;
+    "y") SAY_YES_MODE=1;;
     "?") badUsage "Error: Invalid option"; exit 1 ;;
   esac
 done
@@ -618,6 +644,11 @@ initializeValue $*
 
 # Check if ran with sudo, exit if yes
 checkIfSudo
+
+# Overwrite
+if [ "$PROCESS_MODE" = "block-ota" ] || [ "$PROCESS_MODE" = "unblock-ota" ]; then
+    PACKAGE_NAME=$BLOCK_OTA_PKG
+fi
 
 # Check if inputs are valid before proceeding
 validateInput
@@ -667,13 +698,18 @@ if [ $? -eq 0 ]; then
             if [ $SYS_INCOMPATIBLE -eq 1 ]; then
                 if [ $FORCE_MODE -eq 1 ]; then
                     echo "Incompatible system"
-                    read -p "You are about to force installation despite incompatibility. Depending on the impacted component, your system may break and/or stop booting properly. Continue? (y/Y): " -r
-                    if [[ $REPLY =~ ^[Yy]$ ]]; then
+                    if [ $SAY_YES_MODE -eq 0 ]; then
+                        read -p "You are about to force installation despite incompatibility. Depending on the impacted component, your system may break and/or stop booting properly. Continue? (y/Y): " -r
+                        if [[ $REPLY =~ ^[Yy]$ ]]; then
+                            showDebug "***Forcing Installation***"
+                            CONTINUE_INSTALL=1
+                        else
+                            echo "Process aborted."
+                            exit 0
+                        fi
+                    else
                         showDebug "***Forcing Installation***"
                         CONTINUE_INSTALL=1
-                    else
-                        echo "Process aborted."
-                        exit 0
                     fi
                 else
                     CONTINUE_INSTALL=0
@@ -690,6 +726,14 @@ if [ $? -eq 0 ]; then
                     echo "Installation has been completed successfully"
 
                     runPostInstall # Run post installation command if any
+                    
+                    showDebug "Blocking OTA updates"
+                    if [ $DEBUG_MODE -eq 0 ]; then
+                        ./$SCRIPT --say-yes block-ota &>/dev/null
+                        if [ $? -eq 0 ]; then
+                            echo "OTA updates have been blocked. Run '$SCRIPT unblock-ota' to enable OTA updates again."
+                        fi
+                    fi
                 else
                     echo "Installation failed"
                 fi
@@ -702,13 +746,18 @@ if [ $? -eq 0 ]; then
             if [ $SYS_INCOMPATIBLE -eq 1 ]; then
                 if [ $FORCE_MODE -eq 1 ]; then
                     echo "Package doesn't seem to be installed in your system or you modified some of its files"
-                    read -p "You are about to force uninstallation despite incompatibility. Depending on the impacted component, your system may break and/or stop booting properly. Continue? (y/Y): " -r
-                    if [[ $REPLY =~ ^[Yy]$ ]]; then
+                    if [ $SAY_YES_MODE -eq 0 ]; then
+                        read -p "You are about to force uninstallation despite incompatibility. Depending on the impacted component, your system may break and/or stop booting properly. Continue? (y/Y): " -r
+                        if [[ $REPLY =~ ^[Yy]$ ]]; then
+                            showDebug "***Forcing Uninstallation***"
+                            CONTINUE_UNINSTALL=1
+                        else
+                            echo "Process aborted."
+                            exit 0
+                        fi
+                    else
                         showDebug "***Forcing Uninstallation***"
                         CONTINUE_UNINSTALL=1
-                    else
-                        echo "Process aborted."
-                        exit 0
                     fi
                 else
                     CONTINUE_UNINSTALL=0
@@ -730,13 +779,37 @@ if [ $? -eq 0 ]; then
                 fi
             fi;;
         "reset")
-            remountRootfsRWIfNecessary # rw rootfs is necessary
-            reset_path $TARGET_PATH
-            if [ $? -eq 0 ]; then
-                echo "Reset has been completed successfully"
-                runPostInstall # Run post installation command if any
+            if [ "$PACKAGE_NAME" = "all" ]; then
+                packages_to_reset=($CFG_FOLDER/*)
+                for package in "${packages_to_reset[@]}"
+                do
+                    component_to_reset=$(echo "$package" | sed "s/"${CFG_FOLDER}"\///" | sed 's/\.cfg$//') # Remove top level and file extension
+                    echo "Resetting $component_to_reset"
+                    if [ $DEBUG_MODE -eq 0 ]; then
+                        ./$SCRIPT reset $component_to_reset
+                    fi
+                done
+
+                if [ $? -eq 0 ]; then
+                    echo "All components were reset successfully"
+                    echo "OTA updates will now work again."
+                else
+                    echo "Resetting all components failed"
+                fi
             else
-                echo "Reset failed"
+                remountRootfsRWIfNecessary # rw rootfs is necessary
+                reset_path $TARGET_PATH
+
+                if [ $? -eq 0 ]; then
+                    if [ $TARGET_COMPONENT_PROVIDED -eq 0 ]; then
+                        echo "The package '$PACKAGE_NAME' has been reset successfully"
+                    else
+                        echo "The '$PACKAGE_NAME' has been reset successfully"
+                    fi
+                    runPostInstall # Run post installation command if any
+                else
+                    echo "Reset failed"
+                fi
             fi;;
         "describe")
             if [ "$PACKAGE_DESC" = "" ]; then
@@ -744,8 +817,92 @@ if [ $? -eq 0 ]; then
             else
                 echo -e $PACKAGE_DESC # Echo with \n as newline
             fi;;
+        "block-ota")
+            check_install_compat
+            SYS_INCOMPATIBLE=$?
+
+            CONTINUE_INSTALL=0
+            if [ $SYS_INCOMPATIBLE -eq 1 ]; then
+                echo "OTA updates are already blocked or the current blocking code isn't compatible to your system."
+                if [ $FORCE_MODE -eq 1 ]; then
+                    if [ $SAY_YES_MODE -eq 0 ]; then
+                        read -p "Continue forcing blocking? (y/Y): " -r
+                        if [[ $REPLY =~ ^[Yy]$ ]]; then
+                            showDebug "***Forcing blocking***"
+                            CONTINUE_INSTALL=1
+                        else
+                            echo "Process aborted."
+                            exit 0
+                        fi
+                    else
+                        showDebug "***Forcing blocking***"
+                        CONTINUE_INSTALL=1
+                    fi
+                else
+                    CONTINUE_INSTALL=0
+                fi
+            else
+                CONTINUE_INSTALL=1
+            fi
+
+            if [ $CONTINUE_INSTALL -eq 1 ]; then
+                remountRootfsRWIfNecessary # rw rootfs is necessary
+                install_package
+                if [ $? -eq 0 ]; then
+                    echo "OTA updates are now blocked. Run '$SCRIPT unblock-ota' to unblock OTA updates."
+
+                    runPostInstall # Run post installation command if any
+                else
+                    echo "Blocking OTA updates failed"
+                    exit 1
+                fi
+            else
+                exit 1
+            fi;;
+        "unblock-ota")
+            check_uninstall_compat
+            SYS_INCOMPATIBLE=$?
+
+            CONTINUE_UNINSTALL=0
+            if [ $SYS_INCOMPATIBLE -eq 1 ]; then
+                echo "OTA updates are NOT blocked or some files were modified"
+                if [ $FORCE_MODE -eq 1 ]; then
+                    if [ $SAY_YES_MODE -eq 0 ]; then
+                        read -p "Continue forcing unblocking? (y/Y): " -r
+                        if [[ $REPLY =~ ^[Yy]$ ]]; then
+                            showDebug "***Forcing unblocking***"
+                            CONTINUE_UNINSTALL=1
+                        else
+                            echo "Process aborted."
+                            exit 0
+                        fi
+                    else
+                        showDebug "***Forcing unblocking***"
+                        CONTINUE_UNINSTALL=1
+                    fi
+                else
+                    CONTINUE_UNINSTALL=0
+                fi
+            else
+                CONTINUE_UNINSTALL=1
+            fi
+
+            if [ $CONTINUE_UNINSTALL -eq 1 ]; then
+                remountRootfsRWIfNecessary # rw rootfs is necessary
+                uninstall_package
+                if [ $? -eq 0 ]; then
+                    echo "OTA updates will now work again. Run '$SCRIPT block-ota' to block OTA updates."
+
+                    runPostInstall # Run post installation command if any
+                else
+                    echo "Unblocking OTA updates failed"
+                    exit 1
+                fi
+            else
+                exit 1
+            fi;;
          *)
-            badUsage "Unkown command: $PROCESS_MODE"
+            badUsage "Unknown command: $PROCESS_MODE"
             ;;
     esac
 else
@@ -753,6 +910,5 @@ else
     exit 1
 fi
 
-remountRootfsROIfNecessary # Remount rootfs as read-only
 showDebug "Debug mode on. No actions committed"
 exit 0
